# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5f52\u6863',
                'verbose_name_plural': '\u5f52\u6863',
            },
        ),
    ]
