# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180502_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='guide',
            field=models.TextField(default='', max_length=300, verbose_name='\u5f15\u7528'),
        ),
    ]
