# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='origin',
            field=models.CharField(choices=[('\u539f\u521b', '\u539f\u521b'), ('\u5f15\u7528', '\u5f15\u7528'), ('\u8f6c\u8f7d', '\u8f6c\u8f7d')], default='\u539f\u521b', max_length=100, verbose_name='\u6765\u6e90'),
        ),
    ]
